apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-conf-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: zk-conf-pv-claim
  hostPath:
    path: "/mnt/zkconfig/zookeeper_jaas.conf"