apiVersion: v1
kind: Secret
metadata:
  name: zookeeper-jaas
  namespace: video-server
type: Opaque
stringData:
  zookeeper_jaas.conf: |-
    Server {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        user_super="admin-secret"
        user_kafka="kafka-secret";
    };