version: "3.8"

services: 
  nginxrtmp:
    restart: always
    build:
      dockerfile: ${PROJECT_ROOT}/setup/setup/nginx-rtmp/Dockerfile
      context: ${PROJECT_ROOT}/setup/setup/nginx-rtmp/
    image: iudx_vs/nginx-rtmp
    container_name: nginxrtmp
    volumes:
      - ${PROJECT_ROOT}/setup/certificates:/certificates
    expose:
      - "1935"
      - "8080"
    network_mode: host
