apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      volumes:
        - name: kafka-conf-storage
          persistentVolumeClaim:
            claimName: kafka-conf-pv-claim

        - name: kafka-data-storage
          persistentVolumeClaim:
            claimName: kafka-data-pv-claim

        - name: kafka-certs-storage
          persistentVolumeClaim:
            claimName: kafka-certs-pv-claim


      containers:
      - name: kafka 
        image: confluentinc/cp-kafka:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092

        volumeMounts:
          - mountPath: "/etc/kafka/kafka_jaas.conf"
            name: kafka-conf-storage

          - mountPath: "/var/lib/kafka/data"
            name: kafka-data-storage

          - mountPath: "/etc/kafka/secrets"
            name: kafka-certs-storage

        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-ip-service:2181
          - name: KAFKA_ADVERTISED_LISTENERS
            value: SASL_SSL://videoserver-ip-service:9092
          - name: KAFKA_LISTENERS
            value: SASL_SSL://:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: SASL_SSL:SASL_SSL
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: SASL_SSL
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
            value: PLAIN
          - name: KAFKA_SASL_ENABLED_MECHANISMS
            value: PLAIN
          - name: KAFKA_SSL_KEYSTORE_FILENAME
            value: keystore/kafka.keystore.jks
          - name: KAFKA_SSL_KEYSTORE_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_KEY_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_TRUSTSTORE_FILENAME
            value: truststore/kafka.truststore.jks
          - name: KAFKA_SSL_TRUSTSTORE_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_CLIENT_AUTH
            value: required
          - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            value: ''
          - name: KAFKA_LOG4J_LOGGERS
            value: kafka.authorizer.logger=INFO
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: INFO
          - name: KAFKA_OPTS
            value: -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf
          
        # tty: true
        # livenessProbe:
        #   exec:
        #     command:
        #       - /opt/check.sh
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command:
        #       - /opt/check.sh
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
      