apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-certs-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: kafka-certs-pv-claim
  hostPath:
    path: "/mnt/kafka_certs"