apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: pgdata-pv-claim
  hostPath:
    path: "/mnt/pgdata"