apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: video-server
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config 
            items:
              - key: nginx.conf  
                path: nginx.conf
      
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        volumeMounts:
          - name: nginx-conf
            mountPath: "/etc/nginx/conf.d/nginx.conf"
            subPath: nginx.conf
