apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      
      volumes:
        - name: nginx-conf-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim

        - name: nginx-cert-storage
          persistentVolumeClaim:
            claimName: nginxrtmp-pv-claim
      
      containers:
      - name: nginx-container
        image: vsnginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d/default.conf"
            name: nginx-conf-storage

          - mountPath: "/certificates"
            name: nginx-cert-storage