apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: nginx-pv-claim
  hostPath:
    path: "/mnt/nginxconf/nginx-cms.conf"