apiVersion: v1
kind: Service
metadata:
  name: pgadmin-ip-service
  namespace: video-server
spec:
  type: ClusterIP 
  selector:
    component: pgadmin
  ports:
  - name: pgadmin
    port: 5050
    targetPort: 80

