kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pvc
  namespace: video-server
  labels:
    types: pgadmin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi