apiVersion: v1
kind: Service
metadata:
  name: postgres-ip-service
  namespace: video-server
spec:
  type: ClusterIP 
  selector:
    component: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432

