apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-datalog-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: zk-datalog-pv-claim  
  hostPath:
    path: "/mnt/zkdatalog"