apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://localhost:3100
    editable: false