apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: video-server
spec:
  replicas: 1
  serviceName: kafka-broker
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      volumes:
        - name: kafka-jaas
          secret:
            secretName: kafka-jaas

        - name: kafka-ssl
          secret:
            secretName: kafka-ssl
            items:
              - key: kafka.keystore.jks
                path: kafka.keystore.jks
              - key: kafka.truststore.jks
                path: kafka.truststore.jks
              - key: kafka_password
                path: kafka_password

      containers:
      - name: kafka 
        image: confluentinc/cp-kafka:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9093

        volumeMounts:
          - mountPath: "/var/lib/kafka"
            name: kafka-jaas
            readOnly: true

          - mountPath: "/var/lib/kafka/data"
            name: kafka-data

          - name: kafka-ssl
            mountPath: /etc/kafka/secrets
            readOnly: true

        env:
          - name: HOSTNAME_COMMAND
            value: "echo \"${HOSTNAME}.kafka-broker.video-server.svc.cluster.local\""
          - name: BROKER_ID_COMMAND
            value: "echo ${HOSTNAME##*-}"
          # - name: KAFKA_BROKER_ID
          #   value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service.video-server.svc.cluster.local:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: SASL_SSL://kafka-broker:9093
          - name: KAFKA_LISTENERS
            value: "SASL_SSL://:9093"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: SASL_SSL:SASL_SSL
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: SASL_SSL
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_SSL_KEYSTORE_LOCATION
            value: "/etc/kafka/secrets/kafka.keystore.jks"
          - name: KAFKA_SSL_KEYSTORE_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_KEY_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_KEYSTORE_FILENAME
            value: "kafka.keystore.jks"
          - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            value: ""
          - name: KAFKA_SSL_TRUSTSTORE_LOCATION
            value: "/etc/kafka/secrets/kafka.truststore.jks"
          - name: KAFKA_SSL_TRUSTSTORE_CREDENTIALS
            value: kafka_password
          - name: KAFKA_SSL_TRUSTSTORE_FILENAME
            value: kafka.truststore.jks
          - name: KAFKA_SSL_ENABLED_PROTOCOLS
            value: "TLSv1.2,TLSv1.1,TLSv1"
          - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
            value: PLAIN
          - name: KAFKA_SASL_ENABLED_MECHANISMS
            value: PLAIN
          - name: KAFKA_SSL_CLIENT_AUTH
            value: required
          - name: KAFKA_LOG4J_LOGGERS
            value: kafka.authorizer.logger=INFO
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: INFO
          - name: KAFKA_OPTS
            value: -Djava.security.auth.login.config=/var/lib/kafka/kafka_jaas.conf
          
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi

        # tty: true
        # livenessProbe:
        #   exec:
        #     command:
        #       - /opt/check.sh
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command:
        #       - /opt/check.sh
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
      