apiVersion: v1
kind: Secret
metadata:
  name: kafka-jaas
  namespace: video-server
type: Opaque
stringData:
  kafka_jaas.conf: |-
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        serviceName = "kafka"
        username="kafkabroker"
        password="kafkabroker-secret"
        user_kafkabroker="kafkabroker-secret"
        user_client="client-secret";
    };

    Client {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        username="kafka"
        password="kafka-secret";
    };