global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'cms-metrics'
  metrics_path: '/api/metrics/'
  static_configs:
  - targets: ['localhost:4000']

- job_name: 'lms-metrics'
  honor_labels: true
  static_configs:
  - targets: ['localhost:9091']